### ISSUE TITLE
コーディング規約を決める

### ISSUE THREAD

**Issue by sota1235** [sota1235/Oishinbo#41]
せっかくなので何か規約に則りながら書いてみたい。
ぱっと思いつくのだとCookpadとかGitHubとか？

**Comment by ktarow** [comment]
http://morizyun.github.io/blog/coding-style-ruby-rails-ginza-rb/

**Comment by sota1235** [comment]
https://github.com/styleguide/ruby

**Comment by sota1235** [comment]
https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md

これで行きましょう！
