### ISSUE TITLE
新しいDBのスキーマを考える

### ISSUE THREAD

**Issue by ktarow** [sota1235/Oishinbo#56]
### accounts
1. id, interger not null primary key
2. name, text not null
3. email, text not null
4. profile, text
5. password_hash, text not null
6. created_at datetime
7. updated_at datetime
8. deleted_flag default 0
### account_sections
1. id integer not null primary key
2. section_id, not null
3. account_id, not null
4. created_at, datetime
5. updated_at. datetime
6. deleted_flag, default 0
### sections
1. id, integer not null primary key
2. name, text not null
3. created_at, datetime
4. updated_at, datetime
5. deleted_flag, default 0
### wants
1. id, integer not null primary key
2. account_id
3. restaurant_id
4. comment, text
5. date
6. created_at
7. updated_at
8. done_flag
9. deleted_flag
### participants
1. id, integer not null primary key
2. account_id
3. want_id
4. created_at
5. updated_at
6. deleted_flag
### reports
1. id, integer not null primary key
2. want_id
3. account_id
4. restaurant_id
5. comment
6. created_at
7. updated_at
8. deleted_flag
### photos
1. id, integer not null primary key
2. photo, binary
3. account_id
4. report_id
5. created_at
6. updated_at
7. deleted_flag
### restaurants
1. id, integer not null primary key
2. name
3. name_kana
4. address
5. category
6. tel
7. latitude
8. longitude
9. pc_url
10. mobile_url
11. time_details
12. holiday
13. created_at
14. updated_at
15. created_by
16. updated_by
17. deleted_flag

全体からdeleted_atを削除しました．
また，restaurantsテーブルに関してはユーザー入力のものとぐるなびAPIからのものを分けるために誰が作成したか，更新したかを記録するカラムを追加指定してます(created_by,updated_by)
あとぐるなびAPIから引っ張ってきた情報を直接DBに突っ込んでるから，更新用バッチ的なのが必要になるかも

**Comment by sota1235** [comment]
image_urlを追加でお願いします！

**Comment by ktarow** [comment]
#57 後の新しいDB構成

### accounts
1. id, interger not null primary key
2. name, text not null
3. email, text not null
4. profile, text
5. password_hash, text not null
6. created_at datetime
7. updated_at datetime
8. deleted_flag default 0
9. admin_flag

### account_sections
1. id integer not null primary key
2. section_id, not null
3. account_id, not null
4. created_at, datetime
5. updated_at. datetime
6. deleted_flag, default 0

### sections
1. id, integer not null primary key
2. name, text not null
3. created_at, datetime
4. updated_at, datetime
5. deleted_flag, default 0

### wants
1. id, integer not null primary key
2. account_id
3. restaurant_id
4. created_at
5. updated_at
6. display_flag
7. deleted_flag

### counts
1. id
2. account_id
3. restaurant_id
4. counts
5. created_at
6. updated_at
7. deleted_flag

### comments
1. id
2. restaurant_id
3. account_id
4. comment
5. updated_at
6. created_at
7. deleted_flag

### restaurants(※カッコ内はぐるなびAPIからのレスポンスの型)
1. id(integer)
2. name(string)
3. name_kane(string)
4. address(string)
5. category(string)
6. tel(string)
7. latitude(number[double])
8. longitude(number[double])
9. url(string)
10. url_mobile(string)
11. shop_image1(string)
12. shop_image2(string)
13. created_by
14. updated_by
15. created_at
16. updated_at
17. deleted_flag
18. holiday
19. time_detail

**Comment by ktarow** [comment]
@sota1235 @YuyaAbo 新しく作りなおしたんでレビューお願いしま〜す
