### ISSUE TITLE
店舗情報DB作成

### ISSUE THREAD

**Issue by sota1235** [sota1235/Oishinbo#6]
DBスキーマ作成(第3正規化まで)
- [x] 作成
- [x] レビュー

**Comment by ktarow** [comment]
#### accounts
- id
- 名前
- メールアドレス
- 自己紹介
- パスワード
- 部署_id
- 管理者権限
- updated_at
- deleted_at
- delete_flag

#### sections
- id
- 部署名
- updated_at
- deleted_at
- delete_flag

#### restaurants
- id
- お店の住所(address)
- お店のカテゴリ(category)
- お店の名前(name)
- お店のカナ(name_kana)
- 電話番号(tel)
- 緯度(latitube)
- 経度(longitube)
- PC URL(url)
- MOBILE URL(url_mobile)
- 営業時間(opentime)
- 休業日(holiday)
- updated_at

**Comment by ktarow** [comment]
#### accounts
- id
- 名前
- メールアドレス
- 自己紹介
- パスワード
- 部署_id
- 管理者権限
- updated_at
- deleted_at
- delete_flag

#### sections
- id
- 部署名
- updated_at
- deleted_at
- delete_flag

#### restaurants
- id
- お店の住所(address)
- お店のカテゴリ(category)
- お店の名前(name)
- お店のカナ(name_kana)
- 電話番号(tel)
- 緯度(latitube)
- 経度(longitube)
- PC URL(url)
- MOBILE URL(url_mobile)
- 営業時間(opentime)
- 休業日(holiday)
- updated_at
- deleted_at
- delete_flag

#### evaluations
- id
- account_id
- restaurant_id
- 注文した料理名
- 値段
- コメント
- 写真
- 評価
- 一緒に行った人_id
- updated_at
- deleted_at
- delete_flag

index
- account_id
- restaurant_id

#### wants
- id
- account_id
- restaurant_id
- コメント
- updated_at
- deleted_at
- delete_flag

index
- account_id
- restaurant_id

お店の詳細はぐるなびに遷移させ，こちら側では最低限の情報しか保持しない
外部サービスのアイコンを利用(Gravator)

## URI
- [レストランAPI](http://api.gnavi.co.jp/api/manual/restsearch/)

**Comment by sota1235** [comment]
これも一旦閉じますね
